{% set name = "bugsnag" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d28a0ce3118ab13072c0113761c100164c68ab2416b785fcf5f7d323eaa4dca6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - six >=1.9,<2
    - webob

test:
  imports:
    - bugsnag

about:
  home: https://bugsnag.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatic error monitoring for django, flask, etc.
  dev_url: https://github.com/bugsnag/bugsnag-python

extra:
  recipe-maintainers:
    - tschoonj
