travis:
  secure:
    BINSTAR_TOKEN: B49b4/GRh/+dVp7Mhotoju4j0ICMJ7vwdp2a1MGiTKKrZpakA+2cibMXT5CkFib4SMp5x5q+SUgttdSFm4xt2kWyU+yyy98s9hQHaKJnLMOhi2LldSclAWJu44Xppf2UiytK/xABWOY+2xHDVP9TB8qypAJV/uvPqKKMSizpIXkKKtewlk1nRU8UQpsMuJ2sMlCroiANtLLZMOc1xPdppSpS9xPAldk0QbjYxcXCU1uBFbYQ43bGDLRLFxa4QtJTG62GYQ901QN7tc3HNSljrnsb3aVfXLrBoXGziIkWu8f2rPcrxV4hheopommSJEKTLgUS6fYwsviyDlvVffotZ+axkJg1OutCIQklKG+K1/AFmBaZVGCBRJCmnV0Yg3PwXR4qAWJ3N8lWMr0GagRF3gqWoV8LFTtaphbDWnXzypok2J5XhWJFXWMv0s+zLeEU4W9M4/m21u4/+M9ZDqcyeFVY8Qx7xhOPhgb466JvtGWZtH7oadVj5I65xkOcQbOsQZBnhsPE3fiMLq8soOJGtdBdu2+Nb006wB3O25522l0Kw7GLTBHFXJrFh//QWFknj1rNmwjgyY8xfi2kmTMz07Qm6t4b7iqyjLadtkdT9CYBZ2Bj59EWekVEiDloJ6oI+IXGMeOCHoPSLmrSECTAJCWvJyoPiypKjHmuVaSJ3Ug=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
